services:
  chat-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-ws-api
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
    volumes:
      - ~/.aws:/root/.aws:ro
